spring:
  application:
    name: StocksApp

  datasource:
    url: jdbc:postgresql://db:5432/stock_data

    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka