server:
  port: 8082
spring:
  application:
    name: csv-microservice

  datasource:
    url: jdbc:postgresql://localhost:5433/stock_data
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

