server:
  port: 8081
spring:
  application:
    name: user-microservice

  datasource:
    url: jdbc:postgresql://192.168.100.139:5433/stock_data
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

